name: rki_corona_api
description: Unoffical Api for the RKI. Uses the rki-covid-api from marlon 360 to get information.
version: 2.0.0
repository: https://github.com/RoundedInfinity/rki_corona_api
environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^2.1.0
  test: ^1.16.8
dependencies:
  http: ^1.0.0
