name: rki_corona_api
description: Unoffical Api for the RKI
version: 1.0.0
repository: https://github.com/RoundedInfinity/rki_corona_api
environment:
  sdk: ">=2.10.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
dependencies:
  http: ^0.12.2
